debianism for restoring the clock

diff --git a/hibernate-script/trunk/scriptlets.d/clock b/hibernate-script/trunk/scriptlets.d/clock
--- a/hibernate-script/trunk/scriptlets.d/clock
+++ b/hibernate-script/trunk/scriptlets.d/clock
@@ -5,15 +5,23 @@ AddConfigHandler ClockOptions
 AddConfigHelp "SaveClock restore-only|<boolean>" "Set this to yes to save the system clock before suspending and restore the system clock after resuming. If set to restore-only, the clock will not be saved, only restored - this means suspending is faster, but if your hardware clock drifts significantly, your system clock will drift as well."
 
 ClockSave() {
-    if ! /sbin/hwclock --systohc ; then
-	echo "$EXE: Failed to save system clock - continuing anyway"
+    if [ "x$DISTRIBUTION" = "xdebian" ] ; then
+	/etc/init.d/hwclock.sh stop > /dev/null 2>&1
+    else
+	if ! /sbin/hwclock --systohc ; then
+	    echo "$EXE: Failed to save system clock - continuing anyway"
+	fi
     fi
     return 0  # clock save failing shouldn't be a show stopper, ever.
 }
 
 ClockRestore() {
-    if ! /sbin/hwclock --hctosys ; then
-	echo "$EXE: Failed to restore system clock."
+    if [ "x$DISTRIBUTION" = "xdebian" ] ; then
+	/etc/init.d/hwclock.sh start > /dev/null 2>&1
+    else
+	if ! /sbin/hwclock --hctosys ; then
+	    echo "$EXE: Failed to restore system clock."
+	fi
     fi
     # exit code unchanged.
 }
