Welcome a blacklisted modules option.

diff --git a/hibernate-script/trunk/scriptlets.d/modules b/hibernate-script/trunk/scriptlets.d/modules
--- a/hibernate-script/trunk/scriptlets.d/modules
+++ b/hibernate-script/trunk/scriptlets.d/modules
@@ -4,8 +4,11 @@
 AddConfigHandler ModulesOptions
 AddConfigHelp "UnloadModules <module name> [...]" "Names of modules to unload prior to suspending."
 AddConfigHelp "LoadModules auto|<module name> [...]" "Names of modules to load after resumimg. If auto is specified, the modules that were unloaded previously are loaded."
+AddConfigHelp "UnloadBlacklistedModules <boolean>" "Try to remove any modules that are known to be incompatible with hibernation prior to suspending."
 AddConfigHelp "UnloadAllModules <boolean>" "Try to remove all modules loaded prior to suspending."
 AddConfigHelp "LoadModulesFromFile <filename>" "Load default modules after resuming from a given filename. Each module name must appear on it's own line, and line starting with # are ignored. (eg, Debian's /etc/modules, Gentoo's /etc/modules.autoload)"
+
+MODULES_BLACKLIST_FILE="/etc/hibernate/blacklisted-modules"
 
 CheckModuleSupport() {
     [ -f "/proc/modules" ] && return 0
@@ -17,7 +20,7 @@ CheckModuleSupport() {
 # the kernel's modprobe to /bin/true, and saving the old value.
 SaveKernelModprobe() {
     [ -n "$KERNEL_MODPROBE" ] && return 0
-    [ -f "/proc/sys/kernel/modprobe" ] || return 0
+    [ -r "/proc/sys/kernel/modprobe" ] || return 0
     KERNEL_MODPROBE="`cat /proc/sys/kernel/modprobe`"
     echo "/bin/true" > /proc/sys/kernel/modprobe
     vecho 3 "Saved /proc/sys/kernel/modprobe is $KERNEL_MODPROBE"
@@ -36,7 +39,6 @@ ModulesUnload() {
     CheckModuleSupport || return 0
     local mod
     local ret
-    MOD_UNLOADED=""
     ret=0
     for mod in $MOD_UNLOAD ; do 
 	vecho 2 -n "Unloading module $mod... "
@@ -80,12 +82,115 @@ ModulesUnloadAllOnce() {
     local module
     for module in `awk '($3==0){print $1}' /proc/modules` ;do
 	vecho 2 "Unloading module $module..."
-	modprobe -r $module
+	modprobe -r $module && MOD_UNLOADED="$MOD_UNLOADED $module"
     done
 }
 
+FindModuleDeps() {
+    awk -v "module=$1" '
+function find_related_modules(mod, i, a) {
+    modules[mod] = deps[mod]
+    split(deps[mod], a, ",")
+    for (i in a) {
+        if (a[i] == "") continue
+        if (!modules[a[i]]) {
+            modules[a[i]] = deps[a[i]]
+            find_related_modules(a[i])
+        }
+    }
+}
+
+function top_sort(modules, i, j) {
+    changed = 1
+    while (changed) {
+        changed = 0
+        for(i in modules) {
+            if (modules[i] == "") {
+                print i
+                delete modules[i]
+                for (j in modules) {
+                    sub("^"i",", "", modules[j])
+                    sub(","i",", ",", modules[j])
+                }
+                changed = 1
+            }
+        }
+    }
+}
+
+{ if ($4 != "-") deps[$1] = $4 }
+
+END {
+    find_related_modules(module) # puts results into "modules" array
+    top_sort(modules)
+}
+    ' < /proc/modules
+}
+
+IsInKernelRange() {
+    local kver
+    kver=$1
+    shift
+
+    local min_ver
+    local max_ver
+    while [ -n "$*" ] ; do
+	min_ver=`echo $1 | awk 'BEGIN{FS="[^0-9]"}{print($1*65536)+($2*8)+$3}'`
+	max_ver=`echo $2 | awk 'BEGIN{FS="[^0-9]"}{print($1*65536)+($2*8)+$3}'`
+	shift 2
+	[ "$kver" -ge "$min_ver" -a "$kver" -le "$max_ver" ] && return 0
+    done
+
+    return 1
+}
+
+ModulesUnloadBlacklist() {
+    [ x"$MODULES_UNLOAD_BLACKLIST" = "x1" ] || return 0
+    CheckModuleSupport || return 0
+
+    if [ ! -r "$MODULES_BLACKLIST_FILE" ] ; then
+	vecho 1 "Blacklisted modules file doesn't exist or isn't readable."
+	return 1
+    fi
+
+    local mod
+    local vers
+    local failedmods
+    local kver
+
+    kver=`awk 'BEGIN{FS="[^0-9]"}{print($1*65536)+($2*8)+$3}' /proc/sys/kernel/osrelease`
+
+    # Loop over every line in given file.
+    vecho 2 "Unloading blacklisted modules listed $MODULES_BLACKLIST_FILE" 
+    failedmods=""
+    while : ; do
+	read mod vers
+	[ $? -ne 0 ] && [ -z "$mod" ] && break
+	case $mod in
+	    \#*|"") continue ;;
+	esac
+	IsInKernelRange $kver $vers || continue
+	local deps
+	deps=`FindModuleDeps $mod`
+	vecho 2 "Unloading blacklisted module $mod (and dependencies)"
+	local i
+	for i in $deps ; do
+	    vecho 3 "Unloading $i ..."
+	    if rmmod $i > /dev/null 2>&1 ; then
+		MOD_UNLOADED="$MOD_UNLOADED $i"
+	    else
+		failedmods="$failedmods $i"
+	    fi
+	done
+    done < $MODULES_BLACKLIST_FILE
+
+    [ -z "$failedmods" ] && return 0
+    echo "The following modules failed to unload: $failedmods"
+    return 1
+}
+
 ModulesUnloadAll() {
-    [ x"$MODULES_UNLOADALL" = "x1" ] || return 1
+    [ x"$MODULES_UNLOADALL" = "x1" ] || return 0
     CheckModuleSupport || return 0
 
     local modbefore
@@ -118,7 +223,7 @@ ModulesUnloadAll() {
 
 ModulesLoadFromFile() {
     [ -n "$MODULES_FROMFILE" ] || return 0
-    [ -f "$MODULES_FROMFILE" ] || return 0
+    [ -r "$MODULES_FROMFILE" ] || return 0
     CheckModuleSupport || return 0
     
     local MOD
@@ -151,6 +256,12 @@ ModulesOptions() {
 	    shift
 	    MOD_LOAD="$MOD_LOAD $@"
 	    ;;
+	unloadblacklistedmodules)
+	    if BoolIsOn "$1" "$2" ; then
+		MODULES_UNLOAD_BLACKLIST=1
+		AddSuspendHook 91 ModulesUnloadBlacklist
+	    fi
+	    ;;
 	unloadallmodules)
 	    if BoolIsOn "$1" "$2" ; then
 		MODULES_UNLOADALL=1
@@ -170,6 +281,7 @@ ModulesOptions() {
 	AddSuspendHook 89 SaveKernelModprobe
 	AddResumeHook 92 RestoreKernelModprobe
 	MODPROBE_HOOKED=1
+	MOD_UNLOADED="" # Clear this early on
     fi
     return 0
 }
