Multiple fixes for grub (Carsten Rietzschel).

diff --git a/script/scriptlets.d/grub b/script/scriptlets.d/grub
--- a/script/scriptlets.d/grub
+++ b/script/scriptlets.d/grub
@@ -23,14 +23,14 @@ ChangeGrubMenu() {
 
 RestoreGrubMenu() {
     if [ x"$CHANGE_GRUB_MENU" = "x1" ] ; then
-	vecho 2 "Restoring grub menu ..."
+	vecho 2 "Restoring grub menu."
 	if [ -f $GRUB_MENU_FILE.suspend.sh_bak ] ;then
 	    mv -f "$GRUB_MENU_FILE.suspend.sh_bak" "$GRUB_MENU_FILE"
 	fi
     fi
 }
 
-GrubOptions() {
+GrubConfigOptions() {
     case $1 in
 	changegrubmenu)
 	    BoolIsOn "$1" "$2" && CHANGE_GRUB_MENU=1 || return 0
@@ -47,6 +47,23 @@ GrubOptions() {
 	AddResumeHook 11 RestoreGrubMenu
 	GRUB_HOOKED=1
     fi
+    return 0
+}
+
+GrubCmdlineOptions() {
+    case $1 in
+	-g|--restore-grub)
+	    if [ -x "$SCRIPTLET_DIR/grub" ] ; then
+		$SCRIPTLET_DIR/grub
+		exit 0
+	    fi
+
+	    echo "Grub script not found :("
+	    exit 1
+	    ;;
+	*)
+	    return 1
+    esac
     return 0
 }
 
@@ -69,14 +86,18 @@ if [ "`basename $0`" = "grub" ] ; then
     CHANGE_GRUB_MENU=1
 
     # restore grub and exit
-    echo "Restoring changes in $GRUB_MENU_FILE."
     RestoreGrubMenu
     exit 0
 else
     ## called as part of suspend.sh 
-    AddConfigHandler GrubOptions
+    AddConfigHandler GrubConfigOptions
     AddConfigHelp "ChangeGrubMenu <boolean>" "Change grub's config file to show system is suspended before suspending and restore after resume."
     AddConfigHelp "GrubMenuFile <filename>" "Filename of grub's config file. Default is /boot/grub/grub.conf."
+
+    AddOptionHandler GrubCmdlineOptions
+    AddShortOption 'g'
+    AddLongOption 'restore-grub'
+    AddOptionHelp '-g, --restore-grub' 'Restores the grub menu to normal (use if a suspend was not completed sucessfully).'
 fi
 
 # $Id$
